apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-csi-driver.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    service_name: {{ .Values.config.serviceName }}
    root_dir: {{ .Values.config.rootDir }}
    csi_endpoint: unix:///csi/csi.sock
    {{- with .Values.config.pullConfig }}
    pull_config:
      {{- toYaml . | nindent 6 }}
    {{- end }}