apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-csi-driver.fullname" . }}-docker-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "auths": {{ toJson .Values.config.registryAuths }}
    }
