# Default values for model-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  # Unique service identifier of CSI registration
  serviceName: model.csi.modelpack.org
  # Root working directory for model storage and metadata,
  # must be writable and have enough disk space
  rootDir: /var/lib/model-csi
  registryAuths:
    # registry.example.com:
    #   auth: dXNlcm5hbWU6cGFzc3dvcmQ=
    #   serverscheme: https
  # pullConfig:
  #   # Number of concurrent downloads.
  #   concurrency: 5
  #
  #   # Path to the directory containing Docker config.json file.
  #   # Defaults to /root/.docker
  #   docker_config_dir: ""
  #
  #   # Endpoint of the Dragonfly dfdaemon.
  #   # e.g. unix:////var/run/dragonfly/dfdaemon.sock
  #   dragonfly_endpoint: ""
  #
  #   # URL of a proxy server to use for pulling images.
  #   proxy_url: ""
  #
  #   # Timeout in seconds for pulling a single layer.
  #   pull_layer_timeout_in_seconds: 300

namespace: model-csi

image:
  repository: model-csi-driver
  pullPolicy: IfNotPresent
  tag: latest

registrar:
  image:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    pullPolicy: IfNotPresent
    tag: v2.9.4

resources:
  limits:
    cpu: 1
    memory: 1Gi
    ephemeral-storage: 1Gi
  requests:
    cpu: 0
    memory: 0
    ephemeral-storage: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  name: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
hostAliases: {}